### ISSUE TITLE
CORS headers

### ISSUE THREAD

**Issue by lakshmi-kannan** [soulchild/logos-api#1]
Hi there!

Thanks for hosting the API to get SVGs. I am trying to make a request from my web app and browser complains about CORS headers. Any chance you can set Access-Control-Allow-Origin: * response header when we hit https://logos-api.funkreich.de/?q=vue.js?

![Screenshot from 2019-09-13 17-08-24](https://user-images.githubusercontent.com/1839421/64894961-28625380-d649-11e9-91d9-69af25894b43.png)

**Comment by soulchild** [comment]
Hi Lakshmi,

to be honest, the Logos-API is not supposed to be used by third parties directly which is why I'm reluctant to just allow CORS access from anywhere. Its main purpose is to serve as a backend for my [Sketch logo plugin](https://github.com/soulchild/sketch-logo-fetcher).

May I suggest that you host the API yourself? 

Thanks!

**Comment by lakshmi-kannan** [comment]
@soulchild Thanks for your response! I'll host the API myself then.

**Comment by lakshmi-kannan** [comment]
@soulchild and others -  Here is a PR https://github.com/lakshmi-kannan/logos-api/pull/1 to show how I deployed this to AWS beanstalk. May help someone?
