### ISSUE TITLE
Add VectorLogo.Zone as a source

### ISSUE THREAD

**Issue by fileformat** [soulchild/logos-api#5]
I'd like to add [VectorLogo.Zone](https://www.vectorlogo.zone/) as a source.  I can do the coding for it, but need to know how you would like it to be done.

**Comment by soulchild** [comment]
Nice! 

The current approach is to `git clone` the logos in the [update-logos](https://github.com/soulchild/logos-api/blob/master/bin/update-logos) script and have dedicated [importer modules](https://github.com/soulchild/logos-api/tree/master/lib/sources) per source. 

Is that enough to get you started? Otherwise, just let me know.

**Comment by soulchild** [comment]
Realized via #6

**Comment by soulchild** [comment]
@fileformat Something seems to have changed in your VectorLogoZone repo as the `gh-pages` branch is no longer available. Would you mind submitting a PR to fix this or tell me what needs to be changed [here](https://github.com/soulchild/logos-api/blob/master/bin/update-logos#L43)? Thank you!

**Comment by fileformat** [comment]
Sorry, I switched the branch name to `main`.  I should be able to make a PR tomorrow.

**Comment by soulchild** [comment]
Cheers for the PR, @fileformat!
